# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InformaticsPlugin
                                 A QGIS plugin
 This is a test plug-in for the Geodetic Informatics II class.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-10
        copyright            : (C) 2023 by WSamek PPietrykowska
        email                : 01169913@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load InformaticsPlugin class from file InformaticsPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Informatics_plugin import InformaticsPlugin
    return InformaticsPlugin(iface)
