# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Informatics_plugin_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformaticsPluginDialogBase(object):
    def setupUi(self, InformaticsPluginDialogBase):
        InformaticsPluginDialogBase.setObjectName("InformaticsPluginDialogBase")
        InformaticsPluginDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(InformaticsPluginDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(InformaticsPluginDialogBase)
        self.button_box.accepted.connect(InformaticsPluginDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(InformaticsPluginDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InformaticsPluginDialogBase)

    def retranslateUi(self, InformaticsPluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        InformaticsPluginDialogBase.setWindowTitle(_translate("InformaticsPluginDialogBase", "Informatics Plugin"))
