# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InformaticsPluginDialog
                                 A QGIS plugin
 This is a test plug-in for the Geodetic Informatics II class.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-10
        git sha              : $Format:%H$
        copyright            : (C) 2023 by WSamek PPietrykowska
        email                : 01169913@pw.edu.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.utils import iface
from qgis.core import QgsWkbTypes

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Informatics_plugin_dialog_base.ui'))


class InformaticsPluginDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InformaticsPluginDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.pushbutton_count.clicked.connect(self.count_objects)
        self.pushbutton_showcoordinates.clicked.connect(self.enter_data_on_marked_object)
        self.pushbutton_hight.clicked.connect(self.calculate_height_difference)
        self.pushbutton_calculate.clicked.connect(self.area)
        
    def count_objects(self):
        selected_features = self.mMapLayerComboBox.currentLayer().selectedFeatures()
        number_of_selected_elements = len(selected_features)
        self.label_select.setText(str(number_of_selected_elements))

    def enter_data_on_marked_object(self):
        active_layer = iface.activeLayer()
        sel_features = active_layer.selectedFeatures()
        self.label_active.setText(active_layer.name())

        for feature in sel_features:
            geom = feature.geometry()
            geomSingleType = QgsWkbTypes.isSingleType(geom.wkbType())

            if geom.type() == QgsWkbTypes.PointGeometry:
                if geomSingleType:
                    x = geom.asPoint()
                    self.listObjects.append(f'Point:3{str(x)},3\r\n')
                else:
                    x = geom.asMultiPoint()
                    self.listObjects.append(f'MultiPoint:3{str(x)},3\r\n')
            elif geom.type() == QgsWkbTypes.LineGeometry:
                if geomSingleType:
                    x = geom.asPolyline()
                    self.listObjects.append(f'Polyline:3{str(x)},3\r\n')
                else:
                    x = geom.asMultiPolyline()
                    self.listObjects.append(f'Polyline:3{str(x)},3\r\n')
            elif geom.type() == QgsWkbTypes.PolygonGeometry:
                if geomSingleType:
                    x = geom.asPolygon()
                    self.listObjects.append(f'Polygon:3{str(x)},3\r\n')
                else:
                    x = geom.asMultiPolygon()
                    self.listObjects.append(f'MultiPolygon:3{str(x)},3\r\n')
            else:
                print("Unknown_or_invalid geometry")

    def calculate_height_difference(self):
        selected_layer = self.mMapLayerComboBox.currentLayer()
        number_elements = len(selected_layer.selectedFeatures())
        if number_elements == 2:
            features = selected_layer.selectedFeatures()
            feature1 = features[0]
            feature2 = features[1]

            pnr1 = feature1["nr"]
            px1 = feature1["X"]
            py1 = feature1["Y"]
            pz1 = feature1["H"]

            pnr2 = feature2["nr"]
            px2 = feature2["X"]
            py2 = feature2["Y"]
            pz2 = feature2["H"]

            H = pz2 - pz1
            self.listoHigh.setText(f'The calculated elevation between point {pnr1} and point {pnr2} is {H:.3f} m')
        elif number_elements < 2:
            self.listoHigh.setText("Not enough points selected")
        else:
            self.listoHigh.setText("Too many points were selected")
            
    def area(self):
        selected_layer = self.mMapLayerComboBox.currentLayer()
        number_elements = len(selected_layer.selectedFeatures())

        if number_elements >= 3:
            features = selected_layer.selectedFeatures()
            geom_type = features[0].geometry().type()
            if geom_type == QgsWkbTypes.PolygonGeometry:
                total_area = 0.0
                for feature in features:
                    geom = feature.geometry()
                    if geom.type() == QgsWkbTypes.PolygonGeometry:
                        total_area += geom.area()
                self.label_area.setText(f'Total area: {total_area:.3f} square units')
            else:
                self.label_area.setText("Selected features are not polygons")
        else:
            self.label_area.setText("Not enough polygons selected")
    