# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Informatics_plugin_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformaticsPluginDialogBase(object):
    def setupUi(self, InformaticsPluginDialogBase):
        InformaticsPluginDialogBase.setObjectName("InformaticsPluginDialogBase")
        InformaticsPluginDialogBase.resize(764, 578)
        self.button_box = QtWidgets.QDialogButtonBox(InformaticsPluginDialogBase)
        self.button_box.setGeometry(QtCore.QRect(300, 530, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.listoHigh = QtWidgets.QLabel(InformaticsPluginDialogBase)
        self.listoHigh.setGeometry(QtCore.QRect(280, 160, 191, 71))
        self.listoHigh.setText("")
        self.listoHigh.setWordWrap(True)
        self.listoHigh.setObjectName("listoHigh")
        self.label_area = QtWidgets.QLabel(InformaticsPluginDialogBase)
        self.label_area.setGeometry(QtCore.QRect(280, 60, 55, 16))
        self.label_area.setText("")
        self.label_area.setObjectName("label_area")
        self.pushbutton_calculate = QtWidgets.QPushButton(InformaticsPluginDialogBase)
        self.pushbutton_calculate.setGeometry(QtCore.QRect(280, 90, 93, 28))
        self.pushbutton_calculate.setObjectName("pushbutton_calculate")
        self.one = QtWidgets.QGroupBox(InformaticsPluginDialogBase)
        self.one.setGeometry(QtCore.QRect(20, 20, 241, 201))
        self.one.setTitle("")
        self.one.setObjectName("one")
        self.pushbutton_count = QtWidgets.QPushButton(self.one)
        self.pushbutton_count.setGeometry(QtCore.QRect(20, 160, 93, 28))
        self.pushbutton_count.setObjectName("pushbutton_count")
        self.mMapLayerComboBox = QgsMapLayerComboBox(self.one)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(10, 40, 160, 27))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.Select_layer = QtWidgets.QLabel(self.one)
        self.Select_layer.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.Select_layer.setObjectName("Select_layer")
        self.label_select = QtWidgets.QLabel(self.one)
        self.label_select.setGeometry(QtCore.QRect(20, 110, 55, 16))
        self.label_select.setText("")
        self.label_select.setObjectName("label_select")
        self.two = QtWidgets.QGroupBox(InformaticsPluginDialogBase)
        self.two.setGeometry(QtCore.QRect(20, 220, 241, 331))
        self.two.setTitle("")
        self.two.setObjectName("two")
        self.pushbutton_showcoordinates = QtWidgets.QPushButton(self.two)
        self.pushbutton_showcoordinates.setGeometry(QtCore.QRect(10, 290, 131, 28))
        self.pushbutton_showcoordinates.setObjectName("pushbutton_showcoordinates")
        self.name_active = QtWidgets.QLabel(self.two)
        self.name_active.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.name_active.setObjectName("name_active")
        self.coordinates_of_selected = QtWidgets.QLabel(self.two)
        self.coordinates_of_selected.setGeometry(QtCore.QRect(10, 120, 181, 16))
        self.coordinates_of_selected.setObjectName("coordinates_of_selected")
        self.listObjects = QtWidgets.QTextEdit(self.two)
        self.listObjects.setGeometry(QtCore.QRect(10, 150, 211, 131))
        self.listObjects.setObjectName("listObjects")
        self.label_active = QtWidgets.QLabel(self.two)
        self.label_active.setGeometry(QtCore.QRect(10, 60, 55, 16))
        self.label_active.setText("")
        self.label_active.setObjectName("label_active")
        self.pushbutton_hight = QtWidgets.QPushButton(InformaticsPluginDialogBase)
        self.pushbutton_hight.setGeometry(QtCore.QRect(270, 290, 93, 28))
        self.pushbutton_hight.setObjectName("pushbutton_hight")

        self.retranslateUi(InformaticsPluginDialogBase)
        self.button_box.accepted.connect(InformaticsPluginDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(InformaticsPluginDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InformaticsPluginDialogBase)

    def retranslateUi(self, InformaticsPluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        InformaticsPluginDialogBase.setWindowTitle(_translate("InformaticsPluginDialogBase", "Informatics Plugin"))
        self.pushbutton_calculate.setText(_translate("InformaticsPluginDialogBase", "calculate"))
        self.pushbutton_count.setText(_translate("InformaticsPluginDialogBase", "count"))
        self.Select_layer.setText(_translate("InformaticsPluginDialogBase", "Select layer: "))
        self.pushbutton_showcoordinates.setText(_translate("InformaticsPluginDialogBase", "show coordinates"))
        self.name_active.setText(_translate("InformaticsPluginDialogBase", "Name of active layer:"))
        self.coordinates_of_selected.setText(_translate("InformaticsPluginDialogBase", "Coordinates of selected sites:"))
        self.pushbutton_hight.setText(_translate("InformaticsPluginDialogBase", "hight"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InformaticsPluginDialogBase = QtWidgets.QDialog()
    ui = Ui_InformaticsPluginDialogBase()
    ui.setupUi(InformaticsPluginDialogBase)
    InformaticsPluginDialogBase.show()
    sys.exit(app.exec_())
